### ISSUE TITLE
为什么不写成一个js插件呢，每个客户端200次足够玩的，又不会被限制

### ISSUE THREAD

**Issue by i5ting** [XadillaX/xto#2]
为什么不写成一个js插件呢，每个客户端200次足够玩的，又不会被限制

**Comment by XadillaX** [comment]
https://github.com/XadillaX/workflow-xto

有个 alfred 的 workflow，其它的你们可以自己发挥想象力 233333

而且这个也支持了 CLI。

**Comment by XadillaX** [comment]
https://github.com/XadillaX/workflow-xto

有个 alfred 的 workflow，其它的你们可以自己发挥想象力 233333

而且这个也支持了 CLI。
